### ISSUE TITLE
Where can i get the pretrained_model

### ISSUE THREAD

**Issue by Larissa0829** [Junda24/AFNet#13]
Sorry to bother you, but I would like to ask where can I get your load_weights_folder?

**Comment by Junda24** [comment]
> Sorry to bother you, but I would like to ask where can I get your load_weights_folder?

in readme，https://1drv.ms/u/s!AtFfCZ2Ckf3DghVXXZY611mqxa8B?e=nZ7taR

**Comment by Larissa0829** [comment]
> > Sorry to bother you, but I would like to ask where can I get your load_weights_folder?
> 
> in readme，https://1drv.ms/u/s!AtFfCZ2Ckf3DghVXXZY611mqxa8B?e=nZ7taR

I just clicked on this link, but my network error caused it to not open. Thank you for your reply.

**Comment by Junda24** [comment]
> > > Sorry to bother you, but I would like to ask where can I get your load_weights_folder?
> > 
> > 
> > in readme，https://1drv.ms/u/s!AtFfCZ2Ckf3DghVXXZY611mqxa8B?e=nZ7taR
> 
> I just clicked on this link, but my network error caused it to not open. Thank you for your repl

**Comment by Junda24** [comment]
> > > Sorry to bother you, but I would like to ask where can I get your load_weights_folder?
> > 
> > 
> > in readme，https://1drv.ms/u/s!AtFfCZ2Ckf3DghVXXZY611mqxa8B?e=nZ7taR
> 
> I just clicked on this link, but my network error caused it to not open. Thank you for your reply.

Maybe you can try a different browser or enable a VPN to download it. If that doesn't work, I can send it to your email.

**Comment by Larissa0829** [comment]
> > > > Sorry to bother you, but I would like to ask where can I get your load_weights_folder?
> > > 
> > > 
> > > in readme，https://1drv.ms/u/s!AtFfCZ2Ckf3DghVXXZY611mqxa8B?e=nZ7taR
> > 
> > 
> > I just clicked on this link, but my network error caused it to not open. Thank you for your reply.
> 
> Maybe you can try a different browser or enable a VPN to download it. If that doesn't work, I can send it to your email.

Thank you very much！But I solved the problem by changing a computer.
