### ISSUE TITLE
AF module in your code

### ISSUE THREAD

**Issue by ZYDeeplearning** [Junda24/AFNet#17]
Where is the AF module in your code? I didn't find the corresponding code, only the output of two depth maps

**Comment by Junda24** [comment]
没有单独写一个module，但是在forward过程中有单目和多视角的depth residual的互相作用

**Comment by Junda24** [comment]
> Where is the AF module in your code? I didn't find the corresponding code, only the output of two depth maps

没有单独写一个module，但是在forward过程中有单目和多视角的depth residual的互相作用

**Comment by Junda24** [comment]
> Where is the AF module in your code? I didn't find the corresponding code, only the output of two depth maps

没有单独写一个module，但是在forward过程中有单目和多视角的depth residual的互相作用

**Comment by ZYDeeplearning** [comment]
![image](https://github.com/user-attachments/assets/66670494-7ad2-4f16-931d-b7317f06484c)
Is your ‘depth residual’ referring to this code in the screenshot? It seems to be before the regression estimate. In addition, where the code of the Mw confidence map is embodied is not well understood, thanks!

**Comment by Hamusukesama** [comment]
> > Where is the AF module in your code? I didn't find the corresponding code, only the output of two depth maps
> 
> 没有单独写一个module，但是在forward过程中有单目和多视角的depth residual的互相作用

Same questions. The article says that 'we design the AF module to adaptively select the most accurate depth between the two branches as the final output', which indicates there is a module afterwards, to fuse the depth estimation of the two branches. However, I didn't see the code to do the fusion, using Ms, Mm, and Mw. Besides, is the confidence loss included in the training process? And will the code of 'patchmatch_fusion' be released?

**Comment by Junda24** [comment]
> > > Where is the AF module in your code? I didn't find the corresponding code, only the output of two depth maps
> > 
> > 
> > 没有单独写一个module，但是在forward过程中有单目和多视角的depth residual的互相作用
> 
> Same questions. The article says that 'we design the AF module to adaptively select the most accurate depth between the two branches as the final output', which indicates there is a module afterwards, to fuse the depth estimation of the two branches. However, I didn't see the code to do the fusion, using Ms, Mm, and Mw. Besides, is the confidence loss included in the training process? And will the code of 'patchmatch_fusion' be released?

Sorry for the confusion, this module is designed for noisy poses and will be open-sourced together with the DDAD model soon.

**Comment by chichengfengxue** [comment]
> > > Where is the AF module in your code? I didn't find the corresponding code, only the output of two depth maps
> > 
> > 
> > 没有单独写一个module，但是在forward过程中有单目和多视角的depth residual的互相作用
> 
> Same questions. The article says that 'we design the AF module to adaptively select the most accurate depth between the two branches as the final output', which indicates there is a module afterwards, to fuse the depth estimation of the two branches. However, I didn't see the code to do the fusion, using Ms, Mm, and Mw. Besides, is the confidence loss included in the training process? And will the code of 'patchmatch_fusion' be released?

Refer to this: https://github.com/zhenpeiyang/MVS2D/blob/master/patchmatch_fusion.py
