### ISSUE TITLE
咨询Multi View

### ISSUE THREAD

**Issue by jluwula** [Junda24/AFNet#6]
您好！有问题想请问一下您。想问一下您文章中的multi-view的意思是前后帧吗？是不是多目也适用于您的方法呢？我看您的kitti和DDAD的数据集加载代码，我的理解是前后帧。所以想找您确认一下。

**Comment by Junda24** [comment]
是的，前后帧和多帧都可以的，本质原理上是一样的。只不过多目存在的退化情况会少一些，比如因为车静止导致的退化情况，在多目情况下不存在，但是对于pose噪声的退化情况是都能handle的。

**Comment by jluwula** [comment]
好的，谢谢您的解答！很感谢您！
